In [8]:
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import metrics
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, classification_report , confusion_matrix

# Play Tennis dataset

In [2]:
df = pd.read_csv(r'./play_tennis.csv')
df.head(5)

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [4]:
X = df.drop(columns=['play','day'], axis = 1)
X.head()

    outlook  temp humidity    wind
0     Sunny   Hot     High    Weak
1     Sunny   Hot     High  Strong
2  Overcast   Hot     High    Weak
3      Rain  Mild     High    Weak
4      Rain  Cool   Normal    Weak

In [9]:
data_coloumns = ['outlook','temp','humidity','wind']
le = LabelEncoder()
for column in data_coloumns:
    X[column] = le.fit_transform(X[column])
X.head()

   outlook  temp  humidity  wind
0        2     1         0     1
1        2     1         0     0
2        0     1         0     1
3        1     2         0     1
4        1     0         1     1

In [14]:
splits = range(2,8)
random_states = [0, 42]
result = []
models = []
for split_size in splits:
    split_size = split_size / 10
    for random_state in random_states:
        X_train, X_test, y_train, y_test = train_test_split(X, y_e, test_size=split_size, random_state=random_state , shuffle=True)
        model = GaussianNB()
        model.fit(X_train, y_train)
        models.append(model)
        y_pred = model.predict(X_test)
        accuracy = accuracy_score(y_test, y_pred)
        result.append(["GaussianNB","play_tennis", split_size, random_state, accuracy])

result_df = pd.DataFrame(result, columns=["model","dataset","test_size","random_state","accuracy_score"])
result_df

         model      dataset  test_size  random_state  accuracy_score
0   GaussianNB  play_tennis        0.2             0        0.333333
1   GaussianNB  play_tennis        0.2            42        1.000000
2   GaussianNB  play_tennis        0.3             0        0.400000
3   GaussianNB  play_tennis        0.3            42        0.600000
4   GaussianNB  play_tennis        0.4             0        0.500000
5   GaussianNB  play_tennis        0.4            42        0.666667
6   GaussianNB  play_tennis        0.5             0        0.571429
7   GaussianNB  play_tennis        0.5            42        0.571429
8   GaussianNB  play_tennis        0.6             0        0.444444
9   GaussianNB  play_tennis        0.6            42        0.555556
10  GaussianNB  play_tennis        0.7             0        0.600000
11  GaussianNB  play_tennis        0.7            42        0.600000

# Cancer dataset

In [15]:
df = pd.read_csv(r'./cancer.csv')
df.head(5)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [20]:
X = df.drop(columns=['id','diagnosis', 'Unnamed: 32'], axis = 1)
X.head()

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [23]:
X.isnull().sum().sum()

0

In [25]:
Y = df['diagnosis']
Y.head()

0    M
1    M
2    M
3    M
4    M
Name: diagnosis, dtype: object

In [27]:
splits = range(2,8)
random_states = [0, 42]
models = []
for split_size in splits:
    split_size = split_size / 10
    for random_state in random_states:
        X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=split_size, random_state=random_state , shuffle=True)
        model = GaussianNB()
        model.fit(X_train, y_train)
        models.append(model)
        y_pred = model.predict(X_test)
        accuracy = accuracy_score(y_test, y_pred)
        result.append(["GaussianNB","cancer", split_size, random_state, accuracy])

result_df = pd.DataFrame(result, columns=["model","dataset","test_size","random_state","accuracy_score"])
result_df

         model      dataset  test_size  random_state  accuracy_score
0   GaussianNB  play_tennis        0.2             0        0.333333
1   GaussianNB  play_tennis        0.2            42        1.000000
2   GaussianNB  play_tennis        0.3             0        0.400000
3   GaussianNB  play_tennis        0.3            42        0.600000
4   GaussianNB  play_tennis        0.4             0        0.500000
5   GaussianNB  play_tennis        0.4            42        0.666667
6   GaussianNB  play_tennis        0.5             0        0.571429
7   GaussianNB  play_tennis        0.5            42        0.571429
8   GaussianNB  play_tennis        0.6             0        0.444444
9   GaussianNB  play_tennis        0.6            42        0.555556
10  GaussianNB  play_tennis        0.7             0        0.600000
11  GaussianNB  play_tennis        0.7            42        0.600000
12  GaussianNB       cancer        0.2             0        0.929825
13  GaussianNB       cancer        0.2            42        0.973684
14  GaussianNB       cancer        0.3             0        0.923977
15  GaussianNB       cancer        0.3            42        0.941520
16  GaussianNB       cancer        0.4             0        0.929825
17  GaussianNB       cancer        0.4            42        0.951754
18  GaussianNB       cancer        0.5             0        0.936842
19  GaussianNB       cancer        0.5            42        0.943860
20  GaussianNB       cancer        0.6             0        0.935673
21  GaussianNB       cancer        0.6            42        0.947368
22  GaussianNB       cancer        0.7             0        0.937343
23  GaussianNB       cancer        0.7            42        0.932331

In [28]:
result_df.to_excel("./NB_playtennis.xlsx")