In [2]:
#importing neccesary libraries
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [3]:
#reading the dataset
df = pd.read_csv(r'C:\Users\mca\Documents\ML_220970012\weatherHistory.csv')
df.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [4]:
#getting the datatype and other informations
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Formatted Date            96453 non-null  object
 1   Summary                   96453 non-null  object
 2   Precip Type               95936 non-null  object
 3   Temperature (C)           96453 non-null  float64
 4   Apparent Temperature (C)  96453 non-null  float64
 5   Humidity                  96453 non-null  float64
 6   Wind Speed (km/h)         96453 non-null  float64
 7   Wind Bearing (degrees)    96453 non-null  float64
 8   Visibility (km)           96453 non-null  float64
 9   Loud Cover                96453 non-null  float64
 10  Pressure (millibars)      96453 non-null  float64
 11  Daily Summary             96453 non-null  object
dtypes: float64(8), object(4)
memory usage: 8.8+ MB

In [5]:
#checking for null values
df.isnull().sum()

Formatted Date                0
Summary                       0
Precip Type                 517
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Wind Bearing (degrees)        0
Visibility (km)               0
Loud Cover                    0
Pressure (millibars)          0
Daily Summary                 0
dtype: int64

In [6]:
#dealing with null values
df.fillna(value = '0')

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [7]:
#converting categorical coloumns to numericals
le = LabelEncoder()
data_coloumns = ['Formatted Date' , 'Summary' , 'Precip Type' , 'Daily Summary']
for columns in data_coloumns:
    df[columns] = le.fit_transform(df[columns])
df.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2159,19,0,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,197
1,2160,19,0,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,197
2,2161,17,0,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,197
3,2162,19,0,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,197
4,2163,17,0,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,197

In [24]:
#converting the dataframe into array for calculation
data_array = df.to_numpy()

#function for covariance matrix
def cova(data_array):
    
    #calculating mean
    mean = np.mean(data_array , axis = 0)
    
    #calculating the center point
    center = data_array - mean
    
    #calculating the covariance by multiplying it 
    cov_mat = np.dot(center.T , center) / (len(data_array) - 1)
    
    return cov_mat

cov_m = cova(data_array)
print(cov_m)

[[ 7.74710589e+08  6.41658262e+03 -1.33279942e+02  8.14115679e+03
   9.28832551e+03  2.41334807e+02 -2.54359797e+03 -8.17916088e+04
   1.16714003e+04  0.00000000e+00  4.62002242e+04 -3.80813236e+04]
 [ 6.41658262e+03  1.90226589e+01 -1.74301766e-01  6.10962629e+00
   6.66036210e+00 -9.64399525e-02  1.28399870e-01  1.06734245e+01
   2.56227272e+00  0.00000000e+00  7.31598249e+01  3.86744082e+01]
 [-1.33279942e+02 -1.74301766e-01  1.17670735e-01 -1.70501990e+00
  -1.91459952e+00  1.43715707e-02 -1.36211526e-01 -1.43554768e+00
  -4.42111749e-01  0.00000000e+00  5.01989824e-01 -4.67269144e+00]
 [ 8.14115679e+03  6.10962629e+00 -1.70501990e+00  9.12320371e+01
   1.01418283e+02 -1.18046179e+00  5.91476036e-01  3.07582353e+01
   1.57300713e+01  0.00000000e+00 -6.08574379e+00  2.35904704e+02]
 [ 9.28832551e+03  6.66036210e+00 -1.91459952e+00  1.01418283e+02
   1.14422544e+02 -1.25994104e+00 -4.18943859e+00  3.33463172e+01
   1.71172113e+01  0.00000000e+00 -2.74014554e-01  2.61129065e+02]
 [ 2.41334807e+02 -9.64399525e-02  1.43715707e-02 -1.18046179e+00
  -1.25994104e+00  3.82095917e-02 -3.04002696e-01  1.54205975e-02
  -3.02516856e-01  0.00000000e+00  1.24708609e-01 -4.05008837e+00]
 [-2.54359797e+03  1.28399870e-01 -1.36211526e-01  5.91476036e-01
  -4.18943859e+00 -3.04002696e-01  4.77974641e+01  7.70773944e+01
   2.91997029e+00  0.00000000e+00 -3.98378332e+01 -1.60096408e+00]
 [-8.17916088e+04  1.06734245e+01 -1.43554768e+00  3.07582353e+01
   3.33463172e+01  1.54205975e-02  7.70773944e+01  1.15312007e+04
   2.14252110e+01  0.00000000e+00 -1.46342447e+02  3.24565972e+02]
 [ 1.16714003e+04  2.56227272e+00 -4.42111749e-01  1.57300713e+01
   1.71172113e+01 -3.02516856e-01  2.91997029e+00  2.14252110e+01
   1.75738969e+01  0.00000000e+00  2.93320780e+01  1.08027730e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 4.62002242e+04  7.31598249e+01  5.01989824e-01 -6.08574379e+00
  -2.74014554e-01  1.24708609e-01 -3.98378332e+01 -1.46342447e+02
   2.93320780e+01  0.00000000e+00  1.36819588e+04  3.57464403e+02]
 [-3.80813236e+04  3.86744082e+01 -4.67269144e+00  2.35904704e+02
   2.61129065e+02 -4.05008837e+00 -1.60096408e+00  3.24565972e+02
   1.08027730e+02  0.00000000e+00  3.57464403e+02  3.16692037e+03]]

In [26]:
#function for calculating pca
def pca_f(data_array , num_components):
    
    #calling the cov_matrix function
    cov_m = cova(data_array)
    
    #getting the eigen values and eigen vectors
    eigen_values , eigen_vectors = np.linalg.eig(cov_m)
    
    #selecting the top eigen values
    sor_indices = np.argsort(eigen_values)[::-1]
    eigen_values = eigen_values[sor_indices]
    eigen_vectors = eigen_vectors[:, sor_indices]

    #selecting the top ones now
    top_eig = eigen_vectors[:, :num_components] #reducing the coloumns to num_components
    
    #calculating mean
    mean = np.mean(data_array , axis = 0)
    
    #calculating the center point
    center = data_array - mean
 
    #multiplying the with top eigen vectors to get pca
    pca_f = np.dot(top_eig.T , center.T).T
    return pca_f

principal_comp = pca_f(data_array , 2)
print(principal_comp)

[[-4.60530114e+04  1.32144795e+01]
 [-4.60520123e+04  1.32317423e+01]
 [-4.60510064e+04  1.68693367e+01]
 ...
 [ 4.55010128e+04  2.02893005e+01]
 [ 4.55020138e+04  2.11745626e+01]
 [ 4.55030118e+04  2.02551016e+01]]

In [27]:
#standardising the dataframe
standard = StandardScaler()
data_S = standard.fit_transform(data_array)

#computing the pca with inbuilt function
pca = PCA(n_components=2)
pca_i = pca.fit_transform(data_array)
print(pca_i)

[[-4.60530114e+04 -1.32144795e+01]
 [-4.60520123e+04 -1.32317423e+01]
 [-4.60510064e+04 -1.68693367e+01]
 ...
 [ 4.55010128e+04 -2.02893005e+01]
 [ 4.55020138e+04 -2.11745626e+01]
 [ 4.55030118e+04 -2.02551016e+01]]